config:
    project:
        context: devnet
        name: hotdog-havoc
        templateBaseUrl: https://github.com/Layr-Labs/hourglass-avs-template
        templateVersion: v0.0.9
        version: 0.1.0
version: 0.0.1
